name = "dantier"
compatibility_date = "2026-03-15"
pages_build_output_dir = "./dist"

[vars]
ALLOWED_ORIGINS = "*"
RESEND_FROM_EMAIL = ""
RESEND_FROM_NAME = "Dantier"

[[d1_databases]]
binding = "DB"
database_name = "dantier-reservations"
database_id = "fd1ee827-20ba-4d56-9944-55e586ed7c84"
